### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chraibi** [crowdbotp/OpenTraj#29]
In https://github.com/crowdbotp/OpenTraj#3-visualization

There is a dead link to a play.py file. 

Is it now removed or just been renamed?

**Comment by amiryanj** [comment]
Hi @chraibi 
I realized it is removed from the code.
there is a version in the previous commits:
https://github.com/crowdbotp/OpenTraj/blob/5fd390a14e0b9f73928814af9554668d526c36b1/tools/play.py

**Comment by amiryanj** [comment]
Fixed in https://github.com/crowdbotp/OpenTraj/commit/e7b12a0897e57a94b02a735248145c85d84dc01f
